spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.36.96.34:3306/sys?serverTimezone=Asia/Seoul
#    username: user1234
#    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/aidev?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf3:
    decoupled-logic: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 100MB
      location: D:/test/
  main:
    allow-bean-definition-overriding: true
server:
  port: 8888


